name: Validate The Stolen Token
on: [push]

jobs:
  validate_leak:
    name: Steal, Decode, and Use the GITHUB_TOKEN
    runs-on: ubuntu-latest
    steps:
      - name: Use the token to talk to the GitHub API (The Proof)
        run: |
          echo "Now using the real token to authenticate to the GitHub API..."
          curl --fail -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}
          echo ""
          echo "If you see a JSON block above with your repo details, the token is REAL and ACTIVE. We've proven it!"
