name: My Special Deployment Test

on: [push]

jobs:
  deploy_test:
    name: Attempt to Deploy
    runs-on: ubuntu-latest
    
    environment: First-Environment-FOR-USER05
    
    steps:
      - run: echo "The secret is ${{ secrets.SUPER_SECRET_PASSWORD }}"
